In [1]:
# Basics of Linear Algebra for Machine Learning
## Types of Matrices
## Symmetric Matrix
## Ch10, Page 72

In [2]:
from numpy import array
# define square symmetric 3x3  matrix
A = array([
    [1, 2, 3],
    [2, 1, 2],
    [3, 2, 1]
])
print(A)

# transpose A
Aprime = A.T
print(Aprime)

[[1 2 3]
 [2 1 2]
 [3 2 1]]
[[1 2 3]
 [2 1 2]
 [3 2 1]]
