In [1]:
# Basics of Linear Algebra for Machine Learning
## Types of Matrices
## Orthogonal Matrix
## Ch10, Page 76

In [8]:
from numpy import array
from numpy.linalg import inv
# define orthogonal matrix
Q = array([
    [1, 0],
    [0, -1]
])
print(Q)
# inverse equivalance
V = inv(Q)
print(V)
# transposed
Qt = Q.T
print(Qt)
# identity equivalence
I = Q.dot(Qt)
print(I)


[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[ 1  0]
 [ 0 -1]]
[[1 0]
 [0 1]]
