In [1]:
# Basics of Linear Algebra for Machine Learning
## Types of Matrices
## Triangular Matrix
## Ch10, Page 73

In [2]:
from numpy import array
from numpy import tril
from numpy import triu
# define square 3x3  matrix
A = array([
    [1, 2, 3],
    [2, 1, 2],
    [3, 2, 1]
])
print(A)
# lower triangular matrix
lower = tril(A)
print(lower)
# upper triangular matrix
upper = triu(A)
print(upper)

[[1 2 3]
 [2 1 2]
 [3 2 1]]
[[1 0 0]
 [2 1 0]
 [3 2 1]]
[[1 2 3]
 [0 1 2]
 [0 0 1]]
