In [1]:
# Basics of Linear Algebra for Machine Learning
## Types of Matrices
## Diagonal Matrix
## Ch10, Page 74

In [2]:
from numpy import array
from numpy import diag
# define 5x3  matrix
A = array([
    [1, 2, 3],
    [2, 1, 2],
    [3, 2, 1],
    [1, 2, 3],
    [2, 1, 2]
])
print(A)
# get diagonal vector
d = diag(A)
print(d)
# get diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [2 1 2]
 [3 2 1]
 [1 2 3]
 [2 1 2]]
[1 1 1]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
