In [1]:
# Basics of Linear Algebra for Machine Learning
## Matrix Operations
## Matrix Determinant
## Ch11, Page 84

In [5]:
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A2 = array([
    [2, 1, 1],
    [1, 3, 1],
    [1, 1, 1]
])
print(A)
print(A2)
# calc determinant, ie not invertable
B = det(A)
print(B)

# calc determinant, ie invertable
B2 = det(A2)
print(B2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 1]
 [1 3 1]
 [1 1 1]]
0.0
2.0000000000000004
