In [2]:
# Basics of Linear Algebra for Machine Learning
## Matrix Operations
## Matrix Transpose
## Ch11, Page 80

In [1]:
from numpy import array
# define matrix
A = array([
    [1, 1],
    [0, 1],
    [0, 0]
])
print(A)
# transposed
At = A.T
print(At)

[[1 1]
 [0 1]
 [0 0]]
[[1 0 0]
 [1 1 0]]
