In [1]:
# Basics of Linear Algebra for Machine Learning
## Matrix Operations
## Matrix Rank
## Ch11, Page 85

In [12]:
from numpy import array
from numpy.linalg import matrix_rank
# define scalar
S0 = 1
# define vector
V1 = array([
    [1, 2, 3]
])
V0 = array([
    [0, 0, 0]
])
# define matrix
A1 = array([
    [1, 2],
    [3, 4]
])
A2 = array([
    [1, 3],
    [1, 3]
])
print(S0)
print(V1)
print(V0)
print(A1)
print(A2)
# rank 
s0r = matrix_rank(S0)
print(s0r)
v1r = matrix_rank(V1)
print(v1r)
v0r = matrix_rank(V0)
print(v0r)
a1r = matrix_rank(A1)
print(a1r)
a2r = matrix_rank(A2)
print(a2r)


1
[[1 2 3]]
[[0 0 0]]
[[1 2]
 [3 4]]
[[1 3]
 [1 3]]
1
1
0
2
1
