In [13]:
# Basics of Linear Algebra for Machine Learning
## Sparse Matricies
## Sparse Matricies in Python
## Ch12, Page 94

In [5]:
from numpy import array
from scipy.sparse import csr_matrix
# define dense matrix
A = array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0]
])
print(A)
# convert to sparse using csr method
S = csr_matrix(A)
print(S)
# reconstruct to dense
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
