In [1]:
# Basics of Linear Algebra for Machine Learning
## Tensors in Python
## Tensors Division
## Ch13, Page 103

In [2]:
from numpy import array
# define 1st tensor
T = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]],
    [[19,20,21], [22,23,24], [25,26,27]]
])
# define 2nd tensor
T2 = array([
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]],
    [[3,3,3], [3,3,3], [3,3,3]]
])
print(T.shape)
print(T2.shape)
print(T)
print(T2)
T3 = T / T2
print(T3)

(3, 3, 3)
(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]
[[[1.         2.         3.        ]
  [4.         5.         6.        ]
  [7.         8.         9.        ]]

 [[5.         5.5        6.        ]
  [6.5        7.         7.5       ]
  [8.         8.5        9.        ]]

 [[6.33333333 6.66666667 7.        ]
  [7.33333333 7.66666667 8.        ]
  [8.33333333 8.66666667 9.        ]]]
