In [1]:
# Basics of Linear Algebra for Machine Learning
## Tensors in Python
## Tensors  Product
## Ch13, Page 104

In [9]:
from numpy import array
from numpy import tensordot
# define 1st tensor
T = array([[1,2], [1,2]])
# define 2nd tensor
T2 = array([[3,4], [3,4]])
print(T.shape)
print(T2.shape)
print(T)
print(T2)
T3 = tensordot(T, T2, axes=0)
print(T3)
print(T3.shape)

(2, 2)
(2, 2)
[[1 2]
 [1 2]]
[[3 4]
 [3 4]]
[[[[3 4]
   [3 4]]

  [[6 8]
   [6 8]]]


 [[[3 4]
   [3 4]]

  [[6 8]
   [6 8]]]]
(2, 2, 2, 2)
