In [1]:
# Basics of Linear Algebra for Machine Learning
## Tensors in Python
## Tensors Hadamard Product
## Ch13, Page 102

In [2]:
from numpy import array
# define 1st tensor
T = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]],
    [[19,20,21], [22,23,24], [25,26,27]]
])
# define 2nd tensor
T2 = array([
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]],
    [[3,3,3], [3,3,3], [3,3,3]]
])
print(T.shape)
print(T2.shape)
print(T)
print(T2)
T3 = T * T2
print(T3)

(3, 3, 3)
(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[57 60 63]
  [66 69 72]
  [75 78 81]]]
