In [5]:
# Basics of Linear Algebra for Machine Learning
## Matrix Decomposition
## QR Decomposition
## Ch14, Page 111

In [5]:
from numpy import array
from scipy.linalg import qr
# define square matrix
A = array([
    [1,2],
    [4,5],
    [7,8]
])
print(A)
# factorize
Q, R = qr(A, mode='full')
print(Q)
print(R)
print(A.shape)
print(Q.shape)
print(R.shape)
# reconstruct
B = Q.dot(R)
print(B)
print(B.shape)

[[1 2]
 [4 5]
 [7 8]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.1240384  -9.6011363 ]
 [ 0.          0.90453403]
 [ 0.          0.        ]]
(3, 2)
(3, 3)
(3, 2)
[[1. 2.]
 [4. 5.]
 [7. 8.]]
(3, 2)
