In [5]:
# Basics of Linear Algebra for Machine Learning
## Matrix Decomposition
## LU Decomposition
## Ch14, Page 109

In [6]:
from numpy import array
from scipy.linalg import lu
# define square matrix
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)
# factorize
P, L, U = lu(A)
print(P)
print(L)
print(U)
print(A.shape)
print(P.shape)
print(L.shape)
print(U.shape)
# reconstruct
B = P.dot(L).dot(U)
print(B)
print(B.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
(3, 3)
(3, 3)
(3, 3)
(3, 3)
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
(3, 3)
