In [5]:
# Basics of Linear Algebra for Machine Learning
## Matrix Decomposition
## Cholesky Decomposition
## Ch14, Page 112

In [14]:
from numpy import array
from scipy.linalg import cholesky
# define square matrix
A = array([
    [2,1,1],
    [1,2,1],
    [1,1,2]
])
print(A)
# factorize lower
L = cholesky(A, lower=True)
print(L)
print(A.shape)
print(L.shape)
# reconstruct
B = L.dot(L.T)
print(B)
print(B.shape)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
(3, 3)
(3, 3)
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
(3, 3)


In [16]:
# factorize upper
U = cholesky(A, lower=False)
print(U)
print(A.shape)
print(U.shape)
B = L.dot(L.T)
print(B)
print(B.shape)

[[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]
(3, 3)
(3, 3)
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
(3, 3)
