In [5]:
# Basics of Linear Algebra for Machine Learning
## Eigendecomposition
## Reconstruct Matrix
## Ch15, Page 120

In [2]:
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define square matrix
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)
print(A.shape)
# factorize
evals, evects = eig(A)
# create a matrix from eigenvectors
Q = evects
# create inverse of eigenvectos matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(evals)
# reconstruct
B = Q.dot(L).dot(R)
print(B)
print(B.shape)
print(Q.shape)
print(R.shape)
print(L.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
(3, 3)
(3, 3)
(3, 3)
(3, 3)
