In [5]:
# Basics of Linear Algebra for Machine Learning
## Eigendecomposition
## Confirm an Eigenvector and Eigenvalue
## Ch15, Page 119

In [2]:
from numpy import array
from numpy.linalg import eig
# define square matrix
A = array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(A)
# factorize
evals, evects = eig(A)
print(evals)
print(evects)
print(A.shape)
print(evals.shape)
print(evects.shape)
# confirm first eigenvector
B = A.dot(evects[:,0])
print(B)
C = evects[:,0] * evals[0]
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
(3, 3)
(3,)
(3, 3)
[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]
