In [5]:
# Basics of Linear Algebra for Machine Learning
## Intro to NumPy
## Functions to Create Arrays
## Ch4, Page 18

In [6]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[4.64818826e-310 4.64818810e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 3.95252517e-322]]


In [7]:
# create zero array
from numpy import zeros
a = zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# create ones array
from numpy import ones
a = ones([3,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
