In [4]:
# Basics of Linear Algebra for Machine Learning
## Intro to NumPy
## Combining Arrays
## Ch4, Page 19

In [5]:
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1, 2, 3])
print(a1)
# create second array
a2 = array([4, 5, 6])
print(a2)
# create vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
# create array with hstack
from numpy import hstack
# create first array
a11 = array([1, 2, 3])
print(a11)
# create second array
a21 = array([5, 6, 7])
print(a21)
# create a horizontal stack
a31 = hstack((a11,a21))
print(a31)
print(a31.shape)

[1 2 3]
[5 6 7]
[1 2 3 5 6 7]
(6,)
