In [ ]:
# Basics of Linear Algebra for Machine Learning
## Index, Slice and Reshape NumPy Arrays
## Array Slicing
## Ch5, Page 27

In [14]:
# slice a 1 dim array
from numpy import array
# define array
data = array([1, 2, 3, 4, 5])
# show all
print(data[:])
# show 0th element to 3 over wrt 0th
print(data[0:3])
# show 2th element to 3 over wrt 0th
print(data[2:5])
# show last 2 elements
print(data[-2:])

[1 2 3 4 5]
[1 2 3]
[3 4 5]
[4 5]


In [23]:
# 2 dim slicing
data11 = array([[11, 22, 33],
                [44, 55, 66],
                [77, 88, 99]
               ])
# seperate data
x, y = data11[2,:], data11[:,2]
print(x)
print(y)
# seperate more data
x1, y1 = data11[2,-1:], data11[2,:-1]
print(x1)
print(y1)
# seperate even more data
x2, y2 = data11[2,1:2], data11[2,0:2]
print(x2)
print(y2)

[77 88 99]
[33 66 99]
[99]
[77 88]
[88]
[77 88]


In [32]:
# train and test splitting data
data21 = array([[111, 222, 333],
                [444, 555, 666],
                [777, 888, 999],
                [101, 102, 104]
               ])
# seperate data
split = 2
train, test = data21[:split,:], data21[split:,:]
print(train)
print(test)
# seperate more data
test1, train1 = data21[:,0:1], data21[:,:2]
print(train1)
print(test1)


[[111 222 333]
 [444 555 666]]
[[777 888 999]
 [101 102 104]]
[[111 222]
 [444 555]
 [777 888]
 [101 102]]
[[111]
 [444]
 [777]
 [101]]
