In [1]:
# Basics of Linear Algebra for Machine Learning
## Matricies and Matrix Arithmetic
## Matrix Arithmetic
## Ch9, Page 59

In [3]:
# matrix addition
from numpy import array
# define first matrix
A = array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
#define second matrix
B = array([
    [1, 2, 3],
    [4, 5, 6]
])
print(B)
# add matrices
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [4]:
# matrix subtraction
# define first matrix
A = array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
# define second matrix
B = array([
    [0.1, 0.1, 0.1],
    [0.1, 0.1, 0.1]
])
# subtract matrices
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
[[0.9 1.9 2.9]
 [3.9 4.9 5.9]]
