In [2]:
# Basics of Linear Algebra for Machine Learning
## Matricies and Matrix Arithmetic
## Matrix Multiplication
## Ch9, Page 62

In [3]:
# matrix Hadamard product
from numpy import array
# define first matrix
A = array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
#define second matrix
B = array([
    [2, 2, 2],
    [2, 2, 2]
])
print(B)
# multiply matrices
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[2 2 2]
 [2 2 2]]
[[ 2  4  6]
 [ 8 10 12]]


In [4]:
# matrix division
#define first matrix
A = array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
#define second matrix
B = array([
    [2, 2, 2],
    [2, 2, 2]
])
print(B)
# divide matrices
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[2 2 2]
 [2 2 2]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
