In [1]:
# Basics of Linear Algebra for Machine Learning
## Matricies and Matrix Arithmetic
## Matrix-Matrix Multiplication
## Ch9, Page 64

In [2]:
# matrix dot product
from numpy import array
# define first matrix
A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)
#define second matrix
B = array([
    [1, 2],
    [3, 4]
])
print(B)
# multiply matrices
C = A.dot(B)
print(C)
# multipy matrices with @ operator
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]
