In [1]:
# Basics of Linear Algebra for Machine Learning
## Matricies and Matrix Arithmetic
## Matrix-Vector Multiplication
## Ch9, Page 66

In [3]:
# matrix-vector multiplication
from numpy import array
# define matrix
A = array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A)
print(A.shape)
#define vector
B = array([0.5, 0.5])
print(B)
print(B.shape)
# multiply
C = A.dot(B)
D = A @ B
print(C)
print(D)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[0.5 0.5]
(2,)
[1.5 3.5 5.5]
[1.5 3.5 5.5]
