In [ ]:
# Basics of Linear Algebra for Machine Learning
## Index, Slice and Reshape NumPy Arrays
## Array Reshaping
## Ch5, Page 30

In [1]:
# shape of 1 dim array
from numpy import array
# define array
data = array([1, 2, 3, 4, 5])
print(data.shape)

(5,)


In [4]:
# shape of 2 dim array
data21 = array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]
               ])
print(data21.shape)
print('Rows: %d' % data21.shape[0])
print('Columns: %d' % data21.shape[1])

(3, 3)
Rows: 3
Columns: 3


In [12]:
# reshape 1d to 2d
data31 = array([[111, 222, 333],
                [444, 555, 666],
                [777, 888, 999]
               ])
data41 = data31.reshape(1,9)
data51 = data31.reshape(9,1)
print(data31)
print(data41)
print(data51)
print(data31.shape)
print(data41.shape)
print(data51.shape)


[[111 222 333]
 [444 555 666]
 [777 888 999]]
[[111 222 333 444 555 666 777 888 999]]
[[111]
 [222]
 [333]
 [444]
 [555]
 [666]
 [777]
 [888]
 [999]]
(3, 3)
(1, 9)
(9, 1)


In [13]:
# reshape 2d to 3d vectors
data61 = data31.reshape(data31.shape[0],data31.shape[1],1)
print(data61)
print(data61.shape)

[[[111]
  [222]
  [333]]

 [[444]
  [555]
  [666]]

 [[777]
  [888]
  [999]]]
(3, 3, 1)
