In [1]:
# Basics of Linear Algebra for Machine Learning
## NumPy Array Broadcasting
## Broadcasting in NumPy
## Ch6, Page 36

In [ ]:
## Broadcasting is limited but still useful when arithmatic operations on 2 array dims are equal, or one has dim size 1

In [2]:
# broadcast scalar to 1d array
from numpy import array
# define array
a = array([1, 2, 3, 4, 5])
print(a)
# define scalar
b = 2
print(b)
# broadcast
c = a + b
print(c)

[1 2 3 4 5]
2
[3 4 5 6 7]


In [3]:
# broadcast scalar to 2d array
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]
          ])
print(A)
#define scalar
b = 2
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
# broadcast 1d to 2d array
A11 = array([[1, 2, 3],
            [1, 1, 1]
            ])
print(A11)
# define 1d array
b1 = array([1, 1, 1])
print(b1)
# broadcast
C = A11 + b1
print(C)

[[1 2 3]
 [1 1 1]]
[1 1 1]
[[2 3 4]
 [2 2 2]]
