In [ ]:
# Basics of Linear Algebra for Machine Learning
## Vector and Vector Arithmetic
## Vector Arithmetic
## Ch7, Page 46

In [1]:
# vector addition
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([4, 5, 6])
print(b)
# add vectors
c = a + b
print(c)

[1 2 3]
[4 5 6]
[5 7 9]


In [4]:
# vector subtraction
a11 = array([1.0, 1.0, 1.0])
print(a11)
# define second vector
b11 = array([0.2, 0.2, 0.2])
print(b11)
# subtract vectors
c11 = a11 - b11
print(c11)

[1. 1. 1.]
[0.2 0.2 0.2]
[0.8 0.8 0.8]


In [5]:
# vector multiplication
a21 = array([1, 2, 4])
print(a21)
# define second vector
b21 = array([1, 2, 1])
print(b21)
# multiply vectors
c21 = a21 * b21
print(c21)

[1 2 4]
[1 2 1]
[1 4 4]


In [1]:
# vector division
a31 = array([1, 2, 3])
print(a31)
# define second vector
b31 = array([0.1, 0.2, 0.3])
print(b31)
# divide vectors
c31 = a31 / b31
print(c31)

NameError: name 'array' is not defined